### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by kmallory** [dvandersluis/amcharts.rb#4]
Please add support for amcharts themes.

**Comment by dvandersluis** [comment]
Can you give me an example of what you're trying to do?

**Comment by kmallory** [comment]
Wanted to set a theme from chart creation, e.g. 

 @myreport.x.render_chart(self, :serial, 'x') do |c|
c.theme  = 'light' 

but it seems to be ignored :) 

workaround was to use 

  c.colors = ["#00999f","#d8854f","#eea638","#a7a737","#86a965","#8aabb0","#69c8ff","#cfd27e","#9d9888","#916b8a","#724887","#7256bc"]
 

ugh.
